{{- if .Values.client.ingress.enabled -}}
{{- $fullName := include "elasticsearch.fullname" . -}}
{{- $servicePort := .Values.cluster.service.port -}}
{{- $ingressPath := .Values.client.ingress.path -}}
{{- $root := . }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.client.ingress.labels }}
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .Values.client.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.client.ingress.tls }}
  tls:
  {{- range .Values.client.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.client.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $root.Values.cluster.service.ports.http }}
  {{- end }}
{{- end }}
